### ISSUE TITLE
Add feature save current "profile"

### ISSUE THREAD

**Issue by SrNetoChan** [boundlessgeo/qgis-profiles-plugin#2]
Since changing to a new profile messes with the current users interface. Some user might not like to have their interface all changed without the ability to go back. It would be nice to have a feature that allows the user to save is current interface state before using one of the available profiles.

This could happen:
1 - First time the user tries to apply a profile;
2 - Every time the user apply a profile;

**Comment by alexbruy** [comment]
Partially solved. When QGIS starts first time with enabled Profiles plugin, "default" profile created. Need to find a way to create "default" profile when plugin activated after QGIS start.

**Comment by alexbruy** [comment]
Also added menu entry under `Plugins -> Profiles` to save current QGIS state as profile

**Comment by alexbruy** [comment]
Should be fixed now with Profiles Manager
